const DATABASE_NAME = "";
const TOKENS_COLLECTION = "";
const USERS_COLLECTION = "";
const TOKEN_DURATION = "10m";

module.exports = {
  DATABASE_NAME,
  TOKENS_COLLECTION,
  TOKEN_DURATION,
  USERS_COLLECTION,
};
